google_form/google_form/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls"))
]

google_form/myapp/urls.py
from django.urls import path
from . import views


app_name='myapp'

urlpatterns = [
    path('',views.home,name="home"),
    path('create/',views.create,name='create'),
    path('update_form/<str:pk>',views.update_form,name='update_form'),
    path('response/<str:pk>/view_form', views.get_response_from_user, name='view_form'),
    path('forms/<str:pk>/responses', views.responses, name='responses'),

]

google_form/myapp/models.py
from django.db import models

# Create your models here.

google_form/myapp/views.py
import json

from django.http import Http404, JsonResponse
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse_lazy
from .utils import  Form




form=Form()
# Create your views here.
def get_random_uuid():
    return 'my_simple_uuid'
def home(request):
    forms=form.findall()

    return render(request,"home.html",{"forms":forms})
def create(request):
    pk=form.create()
    return HttpResponseRedirect(reverse_lazy('myapp:update_form',args=[pk]))
def update_form(request,pk):
    if request.method=="POST":
        form_data=json.loads(request.body)
        form.update(pk,form_data)
        return JsonResponse(({
            'saved':'ok'
        }))
    try:
        form_data=form.find(pk)
        return render(request, "update_form.html",{'pk':pk,'form':form_data})
    except Exception as e:
        print(e)
        raise Http404('form did not find')
def get_response_from_user(request,pk):
    if request.method=="POST":
        cd=dict(request.POST)
        print(cd)
        del cd['csrfmiddlewaretoken']
        response={}
        for key,value in cd.items():
            response.update({
                f"reponses.{key}.{value[0]}":1
            })
            print(response)
            form.update_response(pk,response)
        return render(request,'thankyou.html')

    else:
        try:
            form_data=form.find(pk)
            return render(request,"get_response_from_user.html",{
                'pk':pk,
                'form_data':form_data
            })
        except:
            raise  Http404('form not found')
def responses(request,pk):
    form_data=form.find(pk)
    return render(request,'responses.html',{
        'form_data':form_data
    })

google_form/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

{% block content %}
{% endblock content %}




<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% block script %}
{% endblock script %}
</body>
</html>

google_form/templates/get_response_from_user.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{form_data.form_data.title}}</h5>
            <p class="card-text">{{form_data.form_data.description}}</p>
        </div>
    </div>
    <form action="{% url 'myapp:view_form'  pk %}" method="POST">
        {% csrf_token %}
        {% with form_data.form_data.data as questions %}
            {% for questionID,questionData in questions.items %}
                <div class="card mt-2">
                    <div class="card-header fw-bold">
                        Question{{forloop.counter}}
                    </div>
                    <div class="card-body">
                        <div class="form-floating mb-2">
                            <p id="{{questionID}}" class="font-monospace fs-5">{{questionData.questionText}}</p>
                        </div>
                    </div>
                    {% for option in questionData.options %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="{{questionID}}-{{forloop.counter}}" name="{{questionID}}" value={{option}}">
                        <label class="form-check-label for={{questionID}}-{{forloop.counter}}">
                            {{option}}
                        </label>
                    </div>
                    {% endfor %}
                </div>

            {% endfor %}
        {% endwith %}
        <input type="submit" value="submit" class="mt-2">
    </form>
{% endblock %}

google_form/templates/home.html
<!DOCTYPE html>
{% load form_filter %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <style>
        table{
        font-family:arial,sans-serif;
        border-collapse:collapse;
        width:100%;
        }
        td,
        th{
        text-align:left;
        padding:8px;
        }
    </style>
</head>
<body>
<h1>Formbase</h1>
<a href="{% url 'myapp:create' %}"><button>Create form</button></a>
<table>
    <tr>
        <th>Title</th>
        <th>Updated On</th>
        <th>Created On</th>
        <th>View</th>
    </tr>
        {% for i in forms %}
        {% if i.updated %}
            <tr>
                <td>{{i.form_data.title}}</td>
                <td>{{i.updated}}</td>
                <td>{{i.created}}</td>
                <td><a href="{% url 'myapp:update_form' i|lookup:'_id'  %}" target="_blank">Open in new tab</a></td>

            </tr>
        {% endif %}


        {% endfor %}

</table>
</body>
</html>

google_form/templates/responses.html
{% extends 'base.html' %}
{% load form_filter %}



{% block content %}
    <h1>Responses</h1>

    {% with form_data.form_data  as form %}
        {% with form.data as data %}
            {% for questionId,response in form_data.reponses.items %}


                <div class="card">
                    <div class="card-header font-monospace fw-bold">

                        {% with data|lookup:questionId as question %} Q{{forloop.counter}}. {{question.questionText}} {% endwith %}

                    </div>
                    <div class="card-body">
                        <table class="table table=hover">
                            <thead>
                                <tr>
                                    <th scope="col">Option</th>
                                    <th scope="col">Response</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for response,count in response.items %}
                                    <tr>
                                        <td>{{response}}</td>
                                        <td>{{count}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endfor %}
        {% endwith %}
    {% endwith %}
{% endblock %}

google_form/templates/thankyou.html
{% extends 'base.html' %}

{% block content %}
    Thank you.Your response is saved.
{% endblock %}

google_form/templates/update_form.html
{% include 'base.html' %}
{% load static %}
<h1>Update form</h1>
<a href="{% url 'myapp:view_form' pk %}" target="_blank"><button>Share</button></a>
<a href="{% url 'myapp:responses' pk %}"><button>Responses</button></a>

{% block content %}
    <form action="{% url 'myapp:update_form' pk %}" method="POST" id="questionForm">
        {% csrf_token %}
        <button type="submit">Save</button>
       <div class="card" id="form-description">
          <div class="card-header">
            Title and Description
          </div>
          <div class="card-body">
              <div class="form-floating mb-3">
                <input type="text" class="form-control" id="title" placeholder="title" name="title">
                <label for="title">Form title</label>
            </div>
            <div class="form-floating"> <!-- corrected mb-3 here -->
                <textarea class="form-control" placeholder="Description" id="description" name="description"></textarea>
                <label for="description">Form Description</label>
            </div>
          </div>

           <button type="button" id="addQuestion" onclick="addquestion(id)">Add Question</button>
       </div>


    </form>

{% endblock content %}
{% block script %}
    <script src="{% static 'forms.js' %}"></script>
    <script>
        let children =form.children

        children[2].querySelector('[name=title]').value="{{form.form_data.title|escapejs}}"
        children[2].querySelector('[name=description]').value="{{form.form_data.description|escapejs}}"
        {% if form.form_data.data %}
            let addQuestionButtonId='addQuestion';
            let addOptionButtonId,question,option_id,all_opt;
            let i=0;

            {% with form.form_data.data as questions %}
                {% for questionId,questionData in questions.items %}
                                    console.log('Question Data:', {{ questionData|safe }});

                   i={{forloop.counter0|escape}}+3;
                                     console.log('Current value of i:', i);

                    [addQuestionButtonId,addOptionButtonId]=addquestion(addQuestionButtonId,false);
                    children[i].querySelector('.question').value="{{questionData.questionText|escapejs}}"
                    {% for option in questionData.options %}
                       option_id=addOption(addOptionButtonId);
                        all_opt=children[i].querySelector('.allOption').children;
                        all_opt[all_opt.length-1].querySelector(`#${option_id}`).value='{{option}}'
                    {% endfor %}

                {% endfor %}
            {% endwith %}

        {% endif %}



    </script>
{% endblock script %}